package entity;
// Generated 6 f�vr. 2016 21:43:55 by Hibernate Tools 3.6.0

import helper.HQLHelper;
import helper.Helper;
import hibernate.DAO;
import java.awt.Component;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.swing.JComboBox;
import org.hibernate.Query;
import org.hibernate.SQLQuery;
import ui.UILog;
import ui.error.ErrorMsg;

/**
 * ConfigUcs generated by hbm2java
 */
@Entity
@Table(name = "config_warehouse")
public class ConfigWarehouse extends DAO implements java.io.Serializable {

    @Transient
    public static String FINISHED_GOODS = "FINISHED_GOODS";
    @Transient
    public static String PACKAGING = "PACKAGING";
    @Transient
    public static String INVENTORY = "INVENTORY";
    @Transient
    public static String SCRAP = "SCRAP";
    @Transient
    public static String TRANSIT = "TRANSIT";
    @Transient
    public static String WIRES = "WIRES";
    @Transient
    public static String RAW_MATERIAL = "RAW_MATERIAL";

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "config_warehouse_id_seq")
    @SequenceGenerator(name = "config_warehouse_id_seq", sequenceName = "config_warehouse_id_seq", allocationSize = 1)
    private Integer id;

    @Column(name = "warehouse")
    private String warehouse;

    @Column(name = "description")
    private String description;

    @Column(name = "project")
    private String project;

    /**
     * PACKAGING FINISH_GOODS TRANSIT SCRAP BLOQUED';
     */
    @Column(name = "wh_type")
    private String whType;

    public ConfigWarehouse() {
    }

    public ConfigWarehouse(String warehouse, String description, String project, String type) {
        this.warehouse = warehouse;
        this.description = description;
        this.project = project;
        this.whType = type;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getWarehouse() {
        return warehouse;
    }

    public void setWarehouse(String warehouse) {
        this.warehouse = warehouse;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getProject() {
        return project;
    }

    public void setProject(String project) {
        this.project = project;
    }

    public String getWarehouseType() {
        return whType;
    }

    public void setWhType(String whType) {
        this.whType = whType;
    }

    public List<String[]> select() {
        Helper.startSession();

        SQLQuery query = Helper.sess.createSQLQuery(HQLHelper.GET_All_WAREHOUSES);

        Helper.sess.getTransaction().commit();
        return query.list();
    }

    public List<String[]> selectWarehousesByType(String wh_type) {
        Helper.startSession();

        Query query = Helper.sess.createQuery(HQLHelper.GET_WAREHOUSE_BY_TYPE);

        query.setParameter("wh_type", wh_type);
        Helper.sess.getTransaction().commit();
        return query.list();
    }

    public static List selectWarehouse(String warehouse) {
        Helper.startSession();

        Query query = Helper.sess.createQuery(HQLHelper.GET_WAREHOUSE);
        query.setParameter("warehouse", warehouse);

        Helper.sess.getTransaction().commit();
        return query.list();
    }

    public List selectByProject(String project) {
        Helper.startSession();

        Query query = Helper.sess.createQuery(HQLHelper.GET_WAREHOUSE_BY_PROJECT);
        query.setParameter("project", project);

        Helper.sess.getTransaction().commit();
        return query.list();
    }

    public List selectByProjectAndType(String project, String type) {
        Helper.startSession();

        Query query = Helper.sess.createQuery(HQLHelper.GET_WAREHOUSE_BY_PROJECT_AND_TYPE);
        query.setParameter("project", project);
        query.setParameter("wh_type", type);

        Helper.sess.getTransaction().commit();
        return query.list();
    }

    public String getPackagingWh(String project) {
        ConfigWarehouse cw = new ConfigWarehouse();
        List result = cw.selectByProjectAndType(project, "PACKAGING");

        cw = (ConfigWarehouse) result.get(0);
        return (String) cw.getWarehouse();
    }

    /**
     *
     * @param parentUI
     * @param jbox
     * @param project
     * @param warehouse_type
     * @param displayAll
     * @return
     */
    public static JComboBox initWarehouseJBox(Object parentUI, JComboBox jbox, 
            String project, String warehouse_type, boolean displayAll) {
        List result;
        jbox.removeAllItems();
        if (displayAll) {
            //jbox.addItem(new ComboItem("ALL", "ALL"));
            jbox.addItem("ALL");
        }
        if (project != null && !project.isEmpty() && !"null".equals(project)) {
//            switch (warehouse_type){
//                case 0: //Packaging
//                        result = new ConfigWarehouse().selectByProjectAndType(project, "PACKAGING");                    
//                    break;
//                case 1: //Finished Goods
//                        result = new ConfigWarehouse().selectByProjectAndType(project, "FINISHED_GOODS");                    
//                    break;
//                default:
//                        result = null;
//                    break;
//            }
            result = new ConfigWarehouse().selectByProjectAndType(project, warehouse_type);
            if (result.isEmpty()) {
                UILog.severeDialog((Component) parentUI, ErrorMsg.APP_ERR0042);
                UILog.severe(ErrorMsg.APP_ERR0042[1]);
            } else { //Map project data in the list
                for (Object o : result) {
                    ConfigWarehouse cp = (ConfigWarehouse) o;
                    jbox.addItem(cp.getWarehouse());
                }
            }
        } else {
            result = new ConfigWarehouse().selectWarehousesByType(project);
            if (result.isEmpty()) {
                UILog.severeDialog((Component) parentUI, ErrorMsg.APP_ERR0042);
                UILog.severe(ErrorMsg.APP_ERR0042[1]);
            } else { //Map project data in the list
                for (Object o : result) {
                    ConfigWarehouse p = (ConfigWarehouse) o;
                    //jbox.addItem(new ComboItem(p.getWarehouse(), p.getWarehouse()));
                    jbox.addItem(p.getWarehouse());
                }
            }
        }
        return jbox;
    }

    public static JComboBox getWarehouseTypeCombobox(JComboBox j) {

        j.addItem(FINISHED_GOODS);
        j.addItem(PACKAGING);
        j.addItem(INVENTORY);
        j.addItem(SCRAP);
        j.addItem(TRANSIT);
        j.addItem(WIRES);
        j.addItem(RAW_MATERIAL);
        return j;
    }

}
