package entity;

import __main__.GlobalVars;
import gui.packaging.PackagingVars;
import hibernate.DAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * ConfigUcs generated by hbm2java
 */
@Entity
@Table(name = "production_plan")
public class ProductionPlan extends DAO implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "production_plan_id_seq")
    @SequenceGenerator(name = "production_plan_id_seq", sequenceName = "production_plan_id_seq", allocationSize = 1)
    private Integer id;

    @Column(name = "harness_part")
    private String harnessPart;

    @Column(name = "internal_part")
    private String internalPart;

    @Column(name = "create_id")
    private Integer createId;

    @Column(name = "write_id")
    private Integer writeId;

    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name = "write_time")
    private Date writeTime;

    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name = "create_time")
    private Date createTime;

    @Column(name = "create_user")
    private String createUser;

    @Column(name = "write_user")
    private String writeUser;

    @Column(name = "planned_qty", nullable = false)
    private Integer plannedQty;

    public ProductionPlan() {
    }

    public ProductionPlan(String harnessPart, String internalPart, Integer plannedQty) {
        this.harnessPart = harnessPart.toUpperCase();
        this.plannedQty = plannedQty;
        this.internalPart = internalPart.toUpperCase();
        this.createId = PackagingVars.context.getUser().getId();
        this.writeId = PackagingVars.context.getUser().getId();
        this.writeUser = this.createUser = (GlobalVars.CONNECTED_USER.getFirstName()
                + " " + GlobalVars.CONNECTED_USER.getLastName()).toUpperCase();
        this.createTime = this.writeTime = new Date();
    }

    //####################### Getters & Setters ############################
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getHarnessPart() {
        return harnessPart;
    }

    public void setHarnessPart(String harnessPart) {
        this.harnessPart = harnessPart.toUpperCase();
    }

    public String getInternalPart() {
        return internalPart;
    }

    public void setInternalPart(String internalPart) {
        this.internalPart = internalPart.toUpperCase();
    }

    public Integer getCreateId() {
        return createId;
    }

    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    public Integer getWriteId() {
        return writeId;
    }

    public void setWriteId(Integer writeId) {
        this.writeId = writeId;
    }

    public String getWriteTime() {
        return new SimpleDateFormat("YYYY-MM-dd HH:mm:ss").format(writeTime);
    }

    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    public void setWriteTime(String writeTime) {
        try {
            this.writeTime = new SimpleDateFormat("YYYY-MM-dd HH:mm:ss").parse(writeTime);
        } catch (ParseException ex) {

        }
    }

    public String getCreateTime() {
        return new SimpleDateFormat("YYYY-MM-dd HH:mm:ss").format(createTime);
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public void setCreateTime(String createTime) {
        try {
            this.createTime = new SimpleDateFormat("YYYY-MM-DD HH:mm:ss").parse(createTime);
        } catch (ParseException ex) {
            Logger.getLogger(WireConfig.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser.toUpperCase();
    }

    public String getWriteUser() {
        return writeUser;
    }

    public void setWriteUser(String writeUser) {
        this.writeUser = writeUser.toUpperCase();
    }

    public Integer getPlannedQty() {
        return plannedQty;
    }

    public void setPlannedQty(Integer plannedQty) {
        this.plannedQty = plannedQty;
    }

    public void setPlannedQty(int plannedQty) {
        this.plannedQty = plannedQty;
    }

    @Override
    public String toString() {
        return "ProductionPlan{" + "id=" + id + "\n, harnessPart=" + harnessPart + "\n, internalPart=" + internalPart + "\n, createId=" + createId + "\n, writeId=" + writeId + "\n, writeTime=" + writeTime + "\n, createTime=" + createTime + "\n, createUser=" + createUser + "\n, writeUser=" + writeUser + "\n, plannedQty=" + plannedQty + '}';
    }

    @Override
    public int create(Object obj) {
        ProductionPlan aux = (ProductionPlan) obj;
        aux.writeId = aux.createId = GlobalVars.CONNECTED_USER.getId();
        aux.writeUser = aux.createUser = GlobalVars.CONNECTED_USER.getFullName();
        aux.createTime = aux.writeTime = new Date();

        return super.create(aux); 
    }

    @Override
    public void update(Object obj) {
        ProductionPlan aux = (ProductionPlan) obj;
        aux.setWriteId(GlobalVars.CONNECTED_USER.getId());
        aux.setWriteUser(GlobalVars.CONNECTED_USER.getFirstName() + " " + GlobalVars.CONNECTED_USER.getLastName());
        aux.setWriteTime(new Date());
        
        super.update(aux); 
    }

}
