package entity;

import gui.packaging.PackagingVars;
import hibernate.DAO;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * ConfigUcs generated by hbm2java
 */
@Entity
@Table(name = "wire_config")
public class WireConfig extends DAO implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "wire_config_id_seq")
    @SequenceGenerator(name = "wire_config_id_seq", sequenceName = "wire_config_id_seq", allocationSize = 1)
    private Integer id;

    @Column(name = "create_id")
    private Integer createId;

    @Column(name = "write_id")
    private Integer writeId;

    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name = "write_time")
    private Date writeTime;

    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name = "create_time")
    private Date createTime;

    @Column(name = "create_user")
    private String createUser;

    @Column(name = "write_user")
    private String writeUser;

    @Column(name = "project")
    private String project;
    @Column(name = "product_wire_no")
    private String productWireNo;
    @Column(name = "harness_pn")
    private String harnessPn;
    @Column(name = "internal_part")
    private String internalPn;
    @Column(name = "wire_no")
    private String wireNo;
    @Column(name = "operation_no")
    private String operationNo;
    @Column(name = "wire_type")
    private String wireType;
    @Column(name = "spool_pn")
    private String spoolPn;
    @Column(name = "multicore_name")
    private String multicoreName;
    @Column(name = "color")
    private String color;
    @Column(name = "type_")
    private String type;
    @Column(name = "length_")
    private Double length;
    @Column(name = "int_term1")
    private String intTerm1;
    @Column(name = "strip_length1")
    private Double stripLength1;
    @Column(name = "int_seal1")
    private String intSeal1;
    @Column(name = "int_term2")
    private String intTerm2;
    @Column(name = "strip_length2")
    private Double stripLength2;
    @Column(name = "int_seal2")
    private String intSeal2;
    @Column(name = "description")
    private String description;
    @Column(name = "warehouse")
    private String warehouse;
    @Column(name = "wh_location")
    private String whLocation;
    @Column(name = "destination_wh")
    private String destination_wh;
    @Column(name = "card_number")
    private Integer cardNumber;
    @Column(name = "kanban_qty")
    private Integer kanbanQty;
    @Column(name = "bundle_qty")
    private Integer bundleQty;

    @Column(name = "stock", nullable = false, columnDefinition = "integer default 0")
    private Integer stock;

    public WireConfig() {
    }

    public WireConfig(String project, String productWireNo, String harnessPn, String internalPn, String wireNo, String operationNo, String wireType, String spoolPn, String multicoreName, String color, String type, Double length, String intTerm1, Double stripLength1, String intSeal1, String intTerm2, Double stripLength2, String intSeal2, String description, String warehouse, String whLocation, String destination_wh, Integer cardNumber, Integer kanbanQty, Integer bundleQty, Integer stock) {
        this.createId = PackagingVars.context.getUser().getId();
        this.writeId = PackagingVars.context.getUser().getId();
        this.writeUser = this.createUser = PackagingVars.context.getUser().getFirstName() + " " + PackagingVars.context.getUser().getLastName();
        this.createTime = this.writeTime = new Date();
        this.project = project;
        this.productWireNo = productWireNo;
        this.harnessPn = harnessPn;
        this.internalPn = internalPn;
        this.wireNo = wireNo;
        this.operationNo = operationNo;
        this.wireType = wireType;
        this.spoolPn = spoolPn;
        this.multicoreName = multicoreName;
        this.color = color;
        this.type = type;
        this.length = length;
        this.intTerm1 = intTerm1;
        this.stripLength1 = stripLength1;
        this.intSeal1 = intSeal1;
        this.intTerm2 = intTerm2;
        this.stripLength2 = stripLength2;
        this.intSeal2 = intSeal2;
        this.description = description;
        this.warehouse = warehouse;
        this.whLocation = whLocation;
        this.destination_wh = destination_wh;
        this.cardNumber = cardNumber;
        this.kanbanQty = kanbanQty;
        this.bundleQty = bundleQty;
        this.stock = stock;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCreateId() {
        return createId;
    }

    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    public Integer getWriteId() {
        return writeId;
    }

    public void setWriteId(Integer writeId) {
        this.writeId = writeId;
    }

    public Date getWriteTime() {
        return writeTime;
    }

    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    public String getWriteUser() {
        return writeUser;
    }

    public void setWriteUser(String writeUser) {
        this.writeUser = writeUser;
    }

    public String getProject() {
        return project;
    }

    public void setProject(String project) {
        this.project = project;
    }

    public String getProductWireNo() {
        return productWireNo;
    }

    public void setProductWireNo(String productWireNo) {
        this.productWireNo = productWireNo;
    }

    public String getHarnessPn() {
        return harnessPn;
    }

    public void setHarnessPn(String harnessPn) {
        this.harnessPn = harnessPn;
    }

    public String getInternalPn() {
        return internalPn;
    }

    public void setInternalPn(String internalPn) {
        this.internalPn = internalPn;
    }

    public String getWireNo() {
        return wireNo;
    }

    public void setWireNo(String wireNo) {
        this.wireNo = wireNo;
    }

    public String getOperationNo() {
        return operationNo;
    }

    public void setOperationNo(String operationNo) {
        this.operationNo = operationNo;
    }

    public String getWireType() {
        return wireType;
    }

    public void setWireType(String wireType) {
        this.wireType = wireType;
    }

    public String getSpoolPn() {
        return spoolPn;
    }

    public void setSpoolPn(String spoolPn) {
        this.spoolPn = spoolPn;
    }

    public String getMulticoreName() {
        return multicoreName;
    }

    public void setMulticoreName(String multicoreName) {
        this.multicoreName = multicoreName;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Double getLength() {
        return length;
    }

    public void setLength(Double length) {
        this.length = length;
    }

    public String getIntTerm1() {
        return intTerm1;
    }

    public void setIntTerm1(String intTerm1) {
        this.intTerm1 = intTerm1;
    }

    public Double getStripLength1() {
        return stripLength1;
    }

    public void setStripLength1(Double stripLength1) {
        this.stripLength1 = stripLength1;
    }

    public String getIntSeal1() {
        return intSeal1;
    }

    public void setIntSeal1(String intSeal1) {
        this.intSeal1 = intSeal1;
    }

    public String getIntTerm2() {
        return intTerm2;
    }

    public void setIntTerm2(String intTerm2) {
        this.intTerm2 = intTerm2;
    }

    public Double getStripLength2() {
        return stripLength2;
    }

    public void setStripLength2(Double stripLength2) {
        this.stripLength2 = stripLength2;
    }

    public String getIntSeal2() {
        return intSeal2;
    }

    public void setIntSeal2(String intSeal2) {
        this.intSeal2 = intSeal2;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getWarehouse() {
        return warehouse;
    }

    public void setWarehouse(String warehouse) {
        this.warehouse = warehouse;
    }

    public String getWhLocation() {
        return whLocation;
    }

    public void setWhLocation(String whLocation) {
        this.whLocation = whLocation;
    }

    public String getDestination_wh() {
        return destination_wh;
    }

    public void setDestination_wh(String destination_wh) {
        this.destination_wh = destination_wh;
    }

    public Integer getCardNumber() {
        return cardNumber;
    }

    public void setCardNumber(Integer cardNumber) {
        this.cardNumber = cardNumber;
    }

    public Integer getKanbanQty() {
        return kanbanQty;
    }

    public void setKanbanQty(Integer kanbanQty) {
        this.kanbanQty = kanbanQty;
    }

    public Integer getBundleQty() {
        return bundleQty;
    }

    public void setBundleQty(Integer bundleQty) {
        this.bundleQty = bundleQty;
    }

    public Integer getStock() {
        return stock;
    }

    public void setStock(Integer stock) {
        this.stock = stock;
    }

    @Override
    public String toString() {
        return "WireConfig{" + "id=" + id + ", createId=" + createId + ", writeId=" + writeId + ", writeTime=" + writeTime + ", createTime=" + createTime + ", createUser=" + createUser + ", writeUser=" + writeUser + ", project=" + project + ", productWireNo=" + productWireNo + ", harnessPn=" + harnessPn + ", internalPn=" + internalPn + ", wireNo=" + wireNo + ", operationNo=" + operationNo + ", wireType=" + wireType + ", spoolPn=" + spoolPn + ", multicoreName=" + multicoreName + ", color=" + color + ", type=" + type + ", length=" + length + ", intTerm1=" + intTerm1 + ", stripLength1=" + stripLength1 + ", intSeal1=" + intSeal1 + ", intTerm2=" + intTerm2 + ", stripLength2=" + stripLength2 + ", intSeal2=" + intSeal2 + ", description=" + description + ", warehouse=" + warehouse + ", whLocation=" + whLocation + ", destination_wh=" + destination_wh + ", cardNumber=" + cardNumber + ", kanbanQty=" + kanbanQty + ", bundleQty=" + bundleQty + ", stock=" + stock + "}\n";
    }
    
    
    

    //######################################################################   
    /**
     * public List select() { Helper.startSession(); Query query =
     * Helper.sess.createQuery(HQLHelper.);
     * UILog.info(query.getQueryString());
     * Helper.sess.getTransaction().commit(); return query.list(); } *
     */
}
