package entity;

import gui.packaging.PackagingVars;
import hibernate.DAO;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * ConfigUcs generated by hbm2java
 */
@Entity
@Table(name = "wire_booking")
public class WireBooking extends DAO implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "wire_booking_id_seq")
    @SequenceGenerator(name = "wire_booking_id_seq", sequenceName = "wire_booking_id_seq", allocationSize = 1)
    private Integer id;

    @Column(name = "create_id")
    private Integer createId;

    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name = "create_time")
    private Date createTime;

    @Column(name = "create_user")
    private String createUser;

    @Column(name = "wire_no", nullable = false)
    private String wireNo;

    @Column(name = "project", nullable = false) // The project of wire must be specified
    private String project;

    @Column(name = "source_wh", nullable = true) // It can be null in case of inventory operation
    private String sourceWh;

    /**
     * Source warehouse location
     */
    @Column(name = "source_wh_loc") // It can be null in case of inventory operation
    private String sourceWhLoc;

    @Column(name = "dest_wh", nullable = false)
    private String destWh;

    /**
     * Source warehouse location
     */
    @Column(name = "dest_wh_loc", nullable = true)
    private String destWhLoc;

    @Column(name = "qty", nullable = false)
    private Double qty;

    @Column(name = "booking_type", nullable = false) // ['TRANSFER','IN','OUT', 'INVENTORY']
    private String bookingType;

    @Column(name = "wire_type", nullable = true)
    private String wireType;

    public WireBooking() {
    }

    public WireBooking(String wireNo, String project, String sourceWh, String sourceWhLoc, String destWh, String destWhLoc, Double qty, String bookingType) {
        this.wireNo = wireNo;
        this.project = project;
        this.sourceWh = sourceWh;
        this.sourceWhLoc = sourceWhLoc;
        this.destWh = destWh;
        this.destWhLoc = destWhLoc;
        this.qty = qty;
        this.bookingType = bookingType;
        this.createId = PackagingVars.context.getUser().getId();
        this.createUser = PackagingVars.context.getUser().getFirstName() + " " + PackagingVars.context.getUser().getLastName();
        this.createTime = new Date();
    }

    /**
     * Return the booking type according to the given number
     * ['TRANSFER','IN','OUT', 'INVENTORY']
     *
     * @param bookingType
     * @return
     */
    public enum Bookings {

        /**
         *
         */
        TRANSFER(0),
        IN(1),
        OUT(2),
        INVENTORY(3);

        private int type;

        private Bookings(int type) {
            this.type = type;
        }

        public int getTypeCode() {
            return this.type;
        }

    }


    public static String getBookingByType(int bookingType) {
        List<String> bookings = new ArrayList<String>() {
            {
                add("TRANSFER");
                add("IN");
                add("OUT");
                add("INVENTORY");
            }
        };

        return bookings.get(bookingType);
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getWireType() {
        return wireType;
    }

    public void setWireType(String wireType) {
        this.wireType = wireType;
    }
    
    public Integer getCreateId() {
        return createId;
    }

    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    public String getWireNo() {
        return wireNo;
    }

    public void setWireNo(String wireNo) {
        this.wireNo = wireNo;
    }

    public String getProject() {
        return project;
    }

    public void setProject(String project) {
        this.project = project;
    }

    public String getSourceWh() {
        return sourceWh;
    }

    public void setSourceWh(String sourceWh) {
        this.sourceWh = sourceWh;
    }

    public String getSourceWhLoc() {
        return sourceWhLoc;
    }

    public void setSourceWhLoc(String sourceWhLoc) {
        this.sourceWhLoc = sourceWhLoc;
    }

    public String getDestWh() {
        return destWh;
    }

    public void setDestWh(String destWh) {
        this.destWh = destWh;
    }

    public String getDestWhLoc() {
        return destWhLoc;
    }

    public void setDestWhLoc(String destWhLoc) {
        this.destWhLoc = destWhLoc;
    }

    public Double getQty() {
        return qty;
    }

    public void setQty(Double qty) {
        this.qty = qty;
    }

    public String getBookingType() {
        return bookingType;
    }

    public void setBookingType(String bookingType) {
        this.bookingType = bookingType;
    }

    @Override
    public String toString() {
        return "WireBooking{" + "id=\t\t" + id + "\n- createId=\t\t" + createId + "\n- createTime=\t\t" + createTime + "\n- createUser=\t\t" + createUser + "\n- wireNo=\t\t" + wireNo + "\n- project=\t\t" + project + "\n- sourceWh=\t\t" + sourceWh + "\n- sourceWhLoc=\t\t" + sourceWhLoc + "\n- destWh=\t\t" + destWh + "\n- destWhLoc=\t\t" + destWhLoc + "\n- qty=\t\t" + qty + "\n- bookingType=\t\t" + bookingType + '}';
    }

    //######################################################################
    /**
     * public List select() { Helper.startSession(); Query query =
     * Helper.sess.createQuery(HQLHelper.); UILog.info(query.getQueryString());
     * Helper.sess.getTransaction().commit(); return query.list(); } *
     */
    //####################### Getters & Setters ############################
}
