package entity;

import gui.packaging.PackagingVars;
import hibernate.DAO;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * ConfigUcs generated by hbm2java
 */
@Entity
@Table(name = "wire_booking")
public class WireBooking extends DAO implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "wire_booking_id_seq")
    @SequenceGenerator(name = "wire_booking_id_seq", sequenceName = "wire_booking_id_seq", allocationSize = 1)
    private Integer id; 

    @Column(name = "create_id")
    private Integer createId;

    @Column(name = "write_id")
    private Integer writeId;

    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name = "write_time")
    private Date writeTime;

    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name = "create_time")
    private Date createTime;

    @Column(name = "create_user")
    private String createUser;

    @Column(name = "write_user")
    private String writeUser;
    
    @Column(name = "wire_no")
    private String wireNo;
    
    @Column(name = "project")
    private String project;
    
    @Column(name = "source_wh")
    private String sourceWh;
    
    /**
     * Source warehouse location
     */
    @Column(name = "source_wh_loc")
    private String sourceWhLoc;
    
    @Column(name = "dest_wh")
    private String destWh;
    
    /**
     * Source warehouse location
     */
    @Column(name = "dest_wh_loc")
    private String destWhLoc;
    
    @Column(name = "qty", nullable = true)
    private Double qty;
    
    @Column(name = "booking_type")
    private String bookingType;

    public WireBooking() {
    }

    public WireBooking(String wireNo, String project, String sourceWh, String sourceWhLoc, String destWh, String destWhLoc, Double qty, String bookingType) {
        this.wireNo = wireNo;
        this.project = project;
        this.sourceWh = sourceWh;
        this.sourceWhLoc = sourceWhLoc;
        this.destWh = destWh;
        this.destWhLoc = destWhLoc;
        this.qty = qty;
        this.bookingType = bookingType;
        this.createId = PackagingVars.context.getUser().getId();
        this.writeId = PackagingVars.context.getUser().getId();
        this.writeUser = this.createUser = PackagingVars.context.getUser().getFirstName() + " " + PackagingVars.context.getUser().getLastName();
        this.createTime = this.writeTime = new Date();
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCreateId() {
        return createId;
    }

    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    public Integer getWriteId() {
        return writeId;
    }

    public void setWriteId(Integer writeId) {
        this.writeId = writeId;
    }

    public Date getWriteTime() {
        return writeTime;
    }

    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    public String getWriteUser() {
        return writeUser;
    }

    public void setWriteUser(String writeUser) {
        this.writeUser = writeUser;
    }

    public String getWireNo() {
        return wireNo;
    }

    public void setWireNo(String wireNo) {
        this.wireNo = wireNo;
    }

    public String getProject() {
        return project;
    }

    public void setProject(String project) {
        this.project = project;
    }

    public String getSourceWh() {
        return sourceWh;
    }

    public void setSourceWh(String sourceWh) {
        this.sourceWh = sourceWh;
    }

    public String getSourceWhLoc() {
        return sourceWhLoc;
    }

    public void setSourceWhLoc(String sourceWhLoc) {
        this.sourceWhLoc = sourceWhLoc;
    }

    public String getDestWh() {
        return destWh;
    }

    public void setDestWh(String destWh) {
        this.destWh = destWh;
    }

    public String getDestWhLoc() {
        return destWhLoc;
    }

    public void setDestWhLoc(String destWhLoc) {
        this.destWhLoc = destWhLoc;
    }

    public Double getQty() {
        return qty;
    }

    public void setQty(Double qty) {
        this.qty = qty;
    }

    public String getBookingType() {
        return bookingType;
    }

    public void setBookingType(String bookingType) {
        this.bookingType = bookingType;
    }

    @Override
    public String toString() {
        return "WireBooking{" + "id=" + id + ",\n createId=" + createId + ",\n writeId=" + writeId + ",\n writeTime=" + writeTime + ",\n createTime=" + createTime + ",\n createUser=" + createUser + ",\n writeUser=" + writeUser + ",\n wireNo=" + wireNo + ",\n project=" + project + ",\n sourceWh=" + sourceWh + ",\n sourceWhLoc=" + sourceWhLoc + ",\n destWh=" + destWh + ",\n destWhLoc=" + destWhLoc + ",\n qty=" + qty + ",\n bookingType=" + bookingType + '}';
    }
        
    
    //######################################################################
    /**
     * public List select() { Helper.startSession(); Query query =
     * Helper.sess.createQuery(HQLHelper.); UILog.info(query.getQueryString());
     * Helper.sess.getTransaction().commit(); return query.list(); } *
     */
    //####################### Getters & Setters ############################
    

}
