package entity;

import gui.packaging.PackagingVars;
import hibernate.DAO;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * ConfigUcs generated by hbm2java
 */
@Entity
@Table(name = "wire_stock")
public class WireStock extends DAO implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "wire_stock_id_seq")
    @SequenceGenerator(name = "wire_stock_id_seq", sequenceName = "wire_stock_id_seq", allocationSize = 1)
    private Integer id; 

    @Column(name = "wire_no")
    private String wireNo;
    
    @Column(name = "warehouse")
    private String warehouse;
    
    @Column(name = "location")
    private String location;
    
    @Column(name = "qty", nullable = true)
    private Double qty;

    @Override
    public String toString() {
        return "WireStock{" + "id=" + id + "\n, wireNo=" + wireNo + "\n, warehouse=" + warehouse + "\n, location=" + location + "\n, qty=" + qty + '}';
    }
    
    public WireStock(String wireNo, String warehouse, String location, Double qty) {
        this.wireNo = wireNo;
        this.warehouse = warehouse;
        this.location = location;
        this.qty = qty;
    }
    
    public WireStock() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getWireNo() {
        return wireNo;
    }

    public void setWireNo(String wireNo) {
        this.wireNo = wireNo;
    }


    public Double getQty() {
        return qty;
    }

    public void setQty(Double qty) {
        this.qty = qty;
    }

    public String getWarehouse() {
        return warehouse;
    }

    public void setWarehouse(String warehouse) {
        this.warehouse = warehouse;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }
    
    


}
