package gui.about;

import __main__.GlobalVars;
import helper.UIHelper;

/**
 *
 * @author Oussama
 */


public class PACKAGE_07_ABOUT_UI0001 extends javax.swing.JFrame {
    
    private void initLabels() {
        app_name.setText(GlobalVars.APP_NAME+" "+GlobalVars.APP_VERSION);
        rights.setText(GlobalVars.ALL_RIGHTS_RESERVED);
        this.setTitle(GlobalVars.APP_NAME+" "+GlobalVars.APP_VERSION);
        realised.setText(GlobalVars.APP_AUTHOR);
    }
    /**
     * Creates new form MENU_06_ABOUT_UI0001
     */
    public PACKAGE_07_ABOUT_UI0001() {
        initComponents();
        initLabels();
        UIHelper.centerJFrame(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splash_container = new javax.swing.JPanel();
        app_name = new javax.swing.JLabel();
        car_logo = new javax.swing.JLabel();
        realised = new javax.swing.JLabel();
        java_logo = new javax.swing.JLabel();
        java_logo1 = new javax.swing.JLabel();
        java_logo3 = new javax.swing.JLabel();
        rights = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("A propos !");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 51));
        setName("about"); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        splash_container.setBackground(new java.awt.Color(0, 0, 51));

        app_name.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        app_name.setForeground(new java.awt.Color(255, 255, 255));
        app_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        app_name.setText("{APP NAME}");

        car_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        car_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/__main__/images/splash-bg.png"))); // NOI18N
        car_logo.setPreferredSize(new java.awt.Dimension(32, 32));

        realised.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        realised.setForeground(new java.awt.Color(255, 255, 255));
        realised.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        realised.setText("{AUTHOR}");

        java_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/__main__/images/java-logo.png"))); // NOI18N
        java_logo.setPreferredSize(new java.awt.Dimension(32, 32));

        java_logo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java_logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/__main__/images/postgresql-logo.png"))); // NOI18N
        java_logo1.setPreferredSize(new java.awt.Dimension(32, 32));

        java_logo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java_logo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/__main__/images/hibernate-logo.png"))); // NOI18N

        rights.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        rights.setForeground(new java.awt.Color(255, 255, 255));
        rights.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rights.setText("{RIGHTS}");

        javax.swing.GroupLayout splash_containerLayout = new javax.swing.GroupLayout(splash_container);
        splash_container.setLayout(splash_containerLayout);
        splash_containerLayout.setHorizontalGroup(
            splash_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(splash_containerLayout.createSequentialGroup()
                .addComponent(car_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(splash_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(splash_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(realised, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rights, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(app_name, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(splash_containerLayout.createSequentialGroup()
                        .addComponent(java_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(java_logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(java_logo3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        splash_containerLayout.setVerticalGroup(
            splash_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(splash_containerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(app_name)
                .addGap(17, 17, 17)
                .addComponent(car_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(realised)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rights)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(splash_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(java_logo3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(java_logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(java_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splash_container, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splash_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        this.dispose();
    }//GEN-LAST:event_formFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PACKAGE_07_ABOUT_UI0001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PACKAGE_07_ABOUT_UI0001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PACKAGE_07_ABOUT_UI0001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PACKAGE_07_ABOUT_UI0001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PACKAGE_07_ABOUT_UI0001().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel app_name;
    private javax.swing.JLabel car_logo;
    private javax.swing.JLabel java_logo;
    private javax.swing.JLabel java_logo1;
    private javax.swing.JLabel java_logo3;
    private javax.swing.JLabel realised;
    private javax.swing.JLabel rights;
    private javax.swing.JPanel splash_container;
    // End of variables declaration//GEN-END:variables
}
