package gui.logviewer;

import helper.JTextAreaOutputStream;
import java.io.PrintStream;
import javax.swing.JTabbedPane;

/**
 *
 * @author Oussama
 */


public class LOGVIEWER_UI0001 extends javax.swing.JPanel {
    
    private JTabbedPane parent;        

    public LOGVIEWER_UI0001(JTabbedPane rootTabbedPane) {        
        initComponents();
        this.parent = rootTabbedPane;
        
        PrintStream printStream = new PrintStream(new JTextAreaOutputStream(logTextArea));
        System.setOut(printStream);
        System.setErr(printStream);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logJPanel = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        btn_clear = new javax.swing.JButton();

        setBackground(new java.awt.Color(36, 65, 86));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                formComponentRemoved(evt);
            }
        });

        logTextArea.setColumns(20);
        logTextArea.setRows(5);
        logJPanel.setViewportView(logTextArea);

        btn_clear.setText("Effacer");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_clear)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(logJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_clear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        logTextArea.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void formComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentRemoved
        PrintStream standardOut = System.out;
        PrintStream standardErr = System.err;
    }//GEN-LAST:event_formComponentRemoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JScrollPane logJPanel;
    private javax.swing.JTextArea logTextArea;
    // End of variables declaration//GEN-END:variables
}
